---
title: "Introduction to Linux"
author: "Cecina Babich Morrow"
output: pdf_document
date: "2024-02-16"
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)

setwd("/home/aw23877/Documents/statistical_computing_2/intro-to-command-line/")
```

Kernel: Linux, MacOs, Windows
Shell: Ksh, Zsh, Bash, cmd, Powershell
  Like the language you're speaking to the kernel
  Typically interact with shell, not the kernel directly
  Bash is the most common (Bourne Again SHell)
Programs to use the shell: Gnome Terminal, Konsole, MacOs Terminal, Git Bash, Powershell
  The thing you actually open to interact with the shell

## Working with files

### `ls`

`ls` is a command-line utility for listing the contents of a directory. Here are some common flags used with `ls`:

-   `ls -l` gives you a long list of files in the directory, including the permissions, the number of links, the owner, the group, the size, the date, and the name of the file
-   `ls -lt` gives you a long list of files in the directory, sorted by time
-   `ls -ltr` gives you a long list of files in the directory, sorted by time in reverse order `ls -hl` gives you the file sizes in human-readable format

### File permissions

When running `ls -l`, we can see the permissions of each file. For instance, if the permissions are `drwxr-xr-x`, this is how to interpret that:

-   `d` means it is a directory (files start with `-` instead)
-   The `d` or `-` is followed by 3 triples: what is the owner allowed to do, what is the group allowed to do, and what is everyone else allowed to do
-   `rwx` means that someone can read, write, and execute
-   Anything replaced with `-` is an action that that entity cannot do, e.g. `r-x` means that the entity can read and execute, but not write

To change the permissions of a file, you can use the `chmod` command. For example `chmod +x` will add execute permissions to a file for the owner, group, and everyone else.

### Some exercises

Can you mv one file to more than one destination? (Couldn't do this)

What happens if you give cp no destination?

```{bash }
cp data2
```

The result is:

```         
cp: missing destination file operand after 'data2'
Try 'cp --help' for more information.
```

Can you cp, but without being inside the folder it is located in?

```{bash }
cp folder_copy/file2 folder_copy_file2
```

Can you move a folder?

```{bash }
mv folder_copy new_folder_copy
```

How does moving a file onto a folder behave?

```{bash}
mv data2 new_folder_copy
cd new_folder_copy/
ls
```

The results are:

```         
copy-of-data2-but-HERE  data2  file1  file2  file3
```

Can you mv the folder you are actually in?

```{bash }
mv . new_folder_copy2
```

You get `mv: cannot move '.' to 'new_folder_copy2': Device or resource busy`.

## Viewing the contents of files

Some options for viewing the contents of files:

-   `cat`: prints the contents of a file to the terminal
-   `head` & `tail`: prints the first or last 10 lines of a file, respectively (you can change the number of lines printed by running `head -n 5 file.txt`, for example)
-   `tac`: prints the contents of a file in reverse by line (i.e. the last line is printed first)
-   `rev`: prints the contents of a file with the contents of each line reversed by character
-   `uniq`: prints the contents of a file with adjacent identical lines collapsed to one
-   `sort`: prints the contents of a file sorted
-   `less`: allows you to scroll through the contents of a file. If you want to find a specific string, you can type `/` and then the string you want to find, and then press `n` to find the next instance of that string

## Editing files

Some popular text editors:

-   `nano`: a simple text editor
-   `micro`: a modern version of `nano`
-   `emacs`: a powerful text editor with higher learning curve than `nano` / `micro`
-   `jove`: a more minimal version of `emacs`
-   `vim`: a powerful text editor with a steep learning curve that uses lots of keyboard shortcuts

## Searching

### Searching in files

`grep` is a command-line utility for searching plain-text data sets for lines that match a regular expression.

#### Regular expressions

Regular expressions are a way to describe patterns in text. The website [regex101](https://regex101.com/) has resources about regular expressions and the ability to test them.

Some useful regular expression syntax:

* `.` matches any character
* `^` matches the start of a line
* `$` matches the end of a line
* `*` matches the preceding element zero or more times
* `+` matches the preceding element one or more times
* `?` matches the preceding element zero or one time
* `[ab]` matches either "a" or "b"

#### `grep`

Here are some common flags used by `grep`:

* `grep -c`: prints the number of lines that match the pattern
    + If you have multiple targets, it will print the number of matches for each target, e.g. `grep -c "villain" king-lear.txt julius-caesar.txt` yields
    ```         
    king-lear.txt:20
    julius-caesar.txt:4
    ```
* `grep -i`: makes the search case-insensitive
    + Combining `grep -ci` will give you the number of matches case-insensitive
* `grep -n`: prints the line number of each matching line
* `grep -cih`: prints the number of matches case-insensitive and suppresses the file names
* `grep -A2`: prints the line matching the pattern and the two lines following it
* `grep -B2`: prints the line matching the pattern and the two lines preceding it
* `grep -C2`: prints the line matching the pattern and the two lines preceding and following it (alternatively, you could run `grep -A2 -B2`)
* `grep -l`: prints the names of files with matching lines

You can use `grep` to search recursively through directories by using the `-r` flag. You can also use the wildcard `*` to search within files that match a particular pattern, e.g. `grep sparrow a*` will search for the word "sparrow" in all files that start with "a".

#### Searching exercises

To determine which plays contain the word "squirrel", we can run:

```{bash }
grep -l "squirrel" *
```

```
a-midsummer-nights-dream.txt
romeo-and-juliet.txt
```

Similarly, we can list the plays containing "toasted cheese":

```{bash }
grep -l "toasted cheese" *
```

```
henry-vi-part-2.txt
king-lear.txt
merry-wives-of-windsor.txt
```

Now we want to count the number of plays containing the word "confidence":

```{bash }
grep -l "confidence" * | wc -l
```

Note that we are using the `|` operator, which is described in more detail below. We list the plays containing "confidence" using `grep -l` and pipe the results to `wc` to count the number of plays. The command `wc` gives the number of lines, words, and characters in a file, and the `-l` flag extracts only the number of lines, which is in this case the number of plays containing "confidence". We get the result `12`.

To get the line number of the word "folly" in Hamlet:

```{bash }
grep -n "folly" hamlet.txt
```

```
4761:	But that this folly douts it.
```

We want to search for the word "asleep" in plays that have the word "and" in their title:

```{bash }
grep -lc "asleep" *and*
```

```
antony-and-cleopatra.txt
romeo-and-juliet.txt
titus-andronicus.txt
```

To find how many times Lady Macbeth speaks in Hamlet, we use the fact that when someone is speaking, their name is in all caps and it starts the line:

```{bash}
grep -c "^LADY MACBETH" macbeth.txt
```

Note that `^` represents the start of a line in regular expressions. We find that she speaks 60 times in the play.

We want to figure out which act has the most scenes in Henry VI Part 2:

```{bash}

```

To find out how many times both Romeo and Juliet speak in Romeo and Juliet, we can run:

```{bash}
grep -c "^\(ROMEO\|JULIET\)" romeo-and-juliet.txt
```

This command uses the `\|` character to indicate "or" in the regular expression. We find that the two characters speak a combined number of `283` times.

### Searching for files

`find` is a command-line utility for searching for files in a directory hierarchy. `find` has the following syntax: `find [where to look] [what type of file] ["the match you are looking for, in quotes"]`.

## Redirection

Programs can write to the output stream and the error stream. The output stream is where the program writes its normal output, and the error stream is where the program writes its error messages.

The `>` operator redirects the output stream to a new file (or overwrite an existing file). The `>>` operator appends the output stream to a file instead.

### Redirection exercises

Make a new file called “first_50_lines.txt” of the first 50 lines of Romeo and Juliet:

```{bash}
head -n 50 romeo-and-juliet.txt > first_50_lines.txt
```

Make another new file, containing the last 86 lines, of all the plays:

```{bash}
tail -n 86 * > last_86_lines.txt
```

Make a file containing all the lines, from all the plays, containing the word “Queen”:

```{bash}
grep -h "Queen" * > queen_lines.txt
```

Note the use of the `-h` flag to suppress the file names in the output.

Create a file containing the total number of lines spoken by Theseus, Oberon and Lysander in A Midsummer Night’s Dream:

```{bash}
grep -c "^\(THESEUS\|OBERON\|LYSANDER\)" a-midsummer-nights-dream.txt > midsummer_line_count.txt
```

Add the final 100 lines of The Tempest to the `midsummer_line_count.txt` file:

```{bash}
tail -n 100 the-tempest.txt  >> midsummer_line_count.txt
```

## Pipes

The pipe operator `|` sends the output of one program to the input of another program. 

### Pipe exercises

How many `.txt` files are in the `some_plays` folder?

```{bash}
ls | grep -c ".txt"
```

## Working with remote computers

`ssh` stands for "secure shell" and is a command-line utility for logging into a remote machine and executing commands on that machine. The syntax is `ssh [username]@[hostname]`.

## Shell scripts

Rather than typing commands into the terminal interactively, we can save our bash commands into a script file for execution. To run the script, we can use the command `bash [script_name].sh`. By convention, the first line of the script should be `#!/bin/bash`, which tells the shell that this is a bash script and should be interpreted as such.

For more information about bash scripting, see the Ryans Tutorials [Bash Scripting Tutorial](https://ryanstutorials.net/bash-scripting-tutorial/).

